name: Docs Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    uses: fluence-eu/ci-workflows/.github/workflows/ruby-gem-docs-deploy.yml@v6
    permissions:
      contents: read
      pages: write
      id-token: write
      packages: read
